### ISSUE TITLE
Avisar sobre comando nao suportado

### ISSUE THREAD

**Issue by ericmguimaraes** [ericmguimaraes/gaso#15]

**Comment by ericmguimaraes** [comment]
No ObdReader existe um booleano (hasGotDistanceFuel ou algo parecido), precisamos mandar um broadcast desse parametro para todo o app a partir da classe LoggingThread, receber ele na MainActivity (ou mycarfragment talvez? ) e atualizar a informação sobre ser suportado ou não na MainActivity, mostrando um aviso similar ao não tem internet/bluetooth/gps.

**Comment by adrianod1as** [comment]
Acredito que posso chamar do fragment mesmo e aproveitar o mBroadcastReceiver em `MyCarFragment`.
![case](https://cloud.githubusercontent.com/assets/5974969/25878112/9ca8cbaa-34fe-11e7-9d60-f9927907fd7a.png)

A frase esté ok ou sugere outra coisa?
> "Não é possível coletar os dados necessários para a análise."

**Comment by ericmguimaraes** [comment]
Acho que tá legal.

**Comment by ericmguimaraes** [comment]
Digo, o que acha de "Dados para análise de qualidade indisponíveis"?

**Comment by adrianod1as** [comment]
Seria melhor nesse caso, mas a frase fica meio estranha no final. hehe
> Dados para análise da qualidade de combustível indisponíveis.

Por isso uso pronome e verbo.
> Os dados para a análise da qualidade de combustível estão indisponíveis.

**Comment by ericmguimaraes** [comment]
Sim kkk
