### ISSUE TITLE
Colocar dados das avaliacoes nos postos - Firebase

### ISSUE THREAD

**Issue by ericmguimaraes** [ericmguimaraes/gaso#23]

**Comment by ericmguimaraes** [comment]
@adrianodiasx93 voce pode avaliar se aquela estrutura que a gente definiu para o branch de Evaluations no RealTimeDatabase realmente pode ser protegido? eu to achando que não dá, pois o idStation viria antes do userID. No aguardo do feedback para finalizar.

**Comment by adrianod1as** [comment]
Coloca aqui a foto da estrutura atual, por favor.

**Comment by adrianod1as** [comment]
É aquela do vidro o houveram mudanças?

**Comment by ericmguimaraes** [comment]
Percebi que não faz muito sentido criar um branch para isso, já que essas informações estarão dentro dos milestones de qualquer forma, e a diferença do esforço para validar essas informações do milestone ou de um branch exclusivo a partir de uma fonte centralizada é muito similar.

**Comment by adrianod1as** [comment]
Vou fazer a #22. No fim, como ficou a estrutura? Tudo no milestone?

**Comment by ericmguimaraes** [comment]
Olha o `Station` e a HashMap de Evaluations que tem lá.

**Comment by ericmguimaraes** [comment]
E sim, ficou nos milestones, mas vc vai buscar e exibir dessa lista de Evaluations que tao no HashMap. Vamos conversar.
