### ISSUE TITLE
Avisar que não tem suporte para varios combustiveis

### ISSUE THREAD

**Issue by ericmguimaraes** [ericmguimaraes/gaso#24]

**Comment by adrianod1as** [comment]
Gaso é uma aplicação móvel que te auxilia a manter e navegar seu veículo de forma mais eficiente. Na tela Gás é possível obter informações sobre os postos de combustíveis da região, enquanto você pode gerenciar suas despesas com abastecimentos de combustível na tela Gastos. Já na tela inicial, Meu Carro, você pode gerenciar seu carros e obter informações sobre os mesmos conectando o aplicativo ao leitor OBDII plugado no veículo utilizado no momento. Para que você possa obter a melhor experiência possível, separamos algumas sugestões à serem seguidas.
O Gaso depende dos dados obtidos do veículo e seu usuário. Além das informações fornecidas pelo usuário, tais dados são obtidos através do GPS e de uma conexão Bluetooth. Logo, é necessário que tais recursos sejam habilitados e seu uso permitido ao aplicativo. A fim de efetuar a análise do combustível, tais dados são necessários. Quanto mais completos os dados, mais eficiente será a análise. Por completo, nos referimos a quão efetivamente os dados coletados refletem certa atividade. Sugerimos, por exemplo, que todos abastecimentos sejam registrados, e ao registrá-los, que todo os campos do formulário sejam preenchidos. **Infelizmente, o Gaso atualmente não suporta a análise eficiente de combustível de diferentes tipos, então sugerimos que o usuário se restrinja a um tipo apenas.** Ainda sobre abastecimentos, sugerimos que o tanque de combustível seja abastecido completamente a cada abastecimento e que o APP seja conectado ao dispositivo OBD o mais cedo possível para que nenhum dado do abastecimento seja perdido. Atualmente, o Gaso ao efetuar a análise de combustível no tanque procura considerar a quantidade de combustível que foi abastecida em cada posto de combustível, contudo, esse trabalho seria minimizado e a análise seria otimizada se tal combustível pertencesse apenas à um posto. Outra sugestão, seria conectar o aplicativo ao leitor OBDII antes de iniciar um percurso e somente interromper a conexão quando a viagem for concluída. Sugerimos também que ao efetuar a conexão, o veículo seja mantido em solo plano, pois o Gaso coleta o nível de combustível no tanque sempre que conectado ao leitor OBDII, e elevações no solo podem afetar esse cálculo.
Caso você encontre outras medidas que melhoraram sua experiência ao utilizar o Gaso ou tenha sugestões de funcionalidades a serem adicionadas, por favor, sinta-se livre para entrar em contato através do email contato.gaso@gmail.com.

**Comment by adrianod1as** [comment]
Em acordo?

**Comment by ericmguimaraes** [comment]
SIM
