### ISSUE TITLE
Evitar a repetição do dialog abastecimento

### ISSUE THREAD

**Issue by ericmguimaraes** [ericmguimaraes/gaso#27]
- [ ] obd refil
- [ ] location refil

**Comment by adrianod1as** [comment]
Mais detalhes?
Pensei que a repetição já acontecia.

**Comment by ericmguimaraes** [comment]
Na verdade é para evitar a repetição, quando tá no posto ou quando detecta um abastecimento esses dialogs ficam pulsando feito loucos. Precisa de um public static boolean neles que é setado true quando eles já foram mostrados para evitar que varias instancias sejam criadas ao mesmo tempo.

**Comment by adrianod1as** [comment]
Porque impedir a repetição do obd refil?

Se o fluxo em [MyCarFragment](https://github.com/Gaso-UFS/gaso/blob/master/Gaso/app/src/main/java/com/ericmguimaraes/gaso/fragments/MyCarFragment.java) inciado à partir de `case LoggingService.SERVICE_COMBUSTIVE_REFIL:` for seguido, percebe-se que já há uma consequência para ambas respostas do alerta.

No caso de sim (já foi feito um refil), o milestone é atualizado, e `SERVICE_COMBUSTIVE_REFIL` não deve ser mais enviado.

Agora, estou incerto se no caso de não, onde o usuário será enviado para tela de gastos, o milestone está sendo atualizado. Você fez isso?

**Comment by ericmguimaraes** [comment]
Fiz sim! o problema é que a LoggingThread fica enviando o broadcast varias vezes, mesmo enquanto o dialog está aberto.
