### ISSUE TITLE
Corrigir StationDAO addOrUpdate

### ISSUE THREAD

**Issue by ericmguimaraes** [ericmguimaraes/gaso#42]

**Comment by adrianodiasx93** [comment]
Sabe o problema?

**Comment by adrianod1as** [comment]
Sabe o problema? Mais detalhes?

**Comment by ericmguimaraes** [comment]
Só lê o código com calma que vc vai ver. Você colocou uma leitura lá, pelo que eu entendi.

**Comment by adrianod1as** [comment]
`merge(Station stationFromMemory, Station stationFromDatabase)`

```
- merge(dataSnapshot.getValue(Station.class), station)
+ merge(station, dataSnapshot.getValue(Station.class))
```

Tava invertido. (rolling eyes)

**Comment by ericmguimaraes** [comment]
Não só isso

**Comment by ericmguimaraes** [comment]
O problema é no addOrUpdate, vc não tá salvando nada ali, aquilo é uma leitura pelo que to entendendo.

**Comment by adrianod1as** [comment]
Linha 55.
`mDatabase.child(Constants.FIREBASE_STATIONS).child(gasStation.getId()).setValue(gasStation);`

**Comment by adrianod1as** [comment]
Man, na linha 45 tem um 
```
public void addOrUpdate(final Station station){
        // TODO: 11/05/17
}
```
que não faz nada e é utilizado na linha 73 do StationEvaluationHelper.

**Comment by adrianod1as** [comment]
Intencional ou esqueceu de passar o listener?

**Comment by ericmguimaraes** [comment]
Ah, entendi! mas que bom que por isso vc percebeu outro erro! hauhauah Commita ai que eu vou mandar uma mudança para permitir que eu não manda aquele listener. Foi muito esquisito ter um listener num addOrUpdate, e o pior é que eu não tenho certeza se aquele merge vai ser necessario. muitas dúvidas quanto a isso.

**Comment by ericmguimaraes** [comment]
Intencional, não queria passar o listener. Pode chamar o outro metodo com listener passando null e tratar o null dentro?

**Comment by adrianod1as** [comment]
Ai você me diz, programador android sênior. Seria o melhor?

Vai fazer o que quando listener for nulo?

**Comment by ericmguimaraes** [comment]
if(notNull)
   callListener()

**Comment by adrianod1as** [comment]
Sim sim.
Eu pensei que você queria que eu já fizesse a implementação quando fosse nulo.

**Comment by adrianod1as** [comment]
Done.
`if(station.getId() != null && listener != null) {}`

**Comment by ericmguimaraes** [comment]
Mas é isso pow, se não tem listener é pq quem chamou não se importa com o resultado e pode ignorar.

**Comment by ericmguimaraes** [comment]
ei, que isso jovi?

**Comment by adrianod1as** [comment]
FIz antes do ultimo comment. Pera.

**Comment by ericmguimaraes** [comment]
meteu o id ali pq? se o station tiver nullo vai dar merda, e mesmo que o id tiver nullo se o listener não tiver, tem de chamar com o resultado. Quem chamou é que trata.

**Comment by adrianod1as** [comment]
O id ja tava antes na vdd.

Mas se o station tiver nulo e listener não nulo, vai dá merda pois ele vai tentar mergar com um nulo.

**Comment by ericmguimaraes** [comment]
ué, vc checa o nullo no merge... to entendendo nao veio.

**Comment by adrianod1as** [comment]
Assim taria ok pra vc ou tiro o if externo e faco a checagem no merge como sugeriu?
![screen shot 2017-05-11 at 11 36 01 pm](https://cloud.githubusercontent.com/assets/5974969/25980069/afccd672-36a2-11e7-9a50-9d68a22ff47a.png)

**Comment by adrianod1as** [comment]
A ideia eh so proteger contra nulls. 
>  to entendendo nao veio.

**Comment by ericmguimaraes** [comment]
Falta o 
```
if(listenerNotNull)
callListener()
```
em todas as partes que chamam o listener =/

**Comment by adrianod1as** [comment]
Pronto, deixei so o if interno (o do listener) e questiono no merge:
```
if (stationFromMemory == null)
      return  stationFromMemory;
```

**Comment by ericmguimaraes** [comment]
Mano, eu só queria poder chamar o metodo com o listener null. =/ Manda ai...

**Comment by adrianod1as** [comment]
Eu sei, eu sei. =/ Mas com esse codigo ai, vc pode..

**Comment by adrianod1as** [comment]
Inclusive, ja mandei  `dao.addOrUpdate(station, null);` em StationEvaluationHelper.

**Comment by ericmguimaraes** [comment]
eu deixaria o `dao.addOrUpdate(station);` funcionando, esse listener ai é muito tosco, nenhum outro addOrUpdate tem, mas beleza. Moooooove on!!!! estamos demorando demais nisso aqui

**Comment by adrianod1as** [comment]
O fillFields em StationDetails precisa da station, mas so posso passar pra ela depois do merge que usa o firebase. Hence the listener.

Moved.

**Comment by ericmguimaraes** [comment]
caso especifico.

**Comment by ericmguimaraes** [comment]
ow, mas eu não to falando para tirar um e deixar o outro. Era para deixar os 2.

**Comment by ericmguimaraes** [comment]
e o sem listener chama o com listener passando null

**Comment by adrianod1as** [comment]
Done.

https://github.com/Gaso-UFS/gaso/commit/1ee5f6fd0e941ef88618139508df71548e77e24b

Com listener -> tenta o merge
Sem listener -> Só salva.
